In [1]:
from scipy.signal import correlate2d, convolve2d
import torch

In [2]:
a = torch.tensor([[1.1, 1.2, 1.3],
                  [2.1, 2.2, 2.3],
                  [3.1, 3.2, 3.3]])

In [3]:
conv_pytorch = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3))
with torch.no_grad():
    conv_pytorch.bias.zero_()
    
conv_pytorch.weight

Parameter containing:
tensor([[[[ 0.1189, -0.1202,  0.2584],
          [-0.2276, -0.1327, -0.0296],
          [ 0.1741, -0.3225, -0.0288]]]], requires_grad=True)

In [4]:
conv_weight_numpy = conv_pytorch.weight.detach().numpy().reshape(3, 3)
conv_weight_numpy

array([[ 0.11893535, -0.12021737,  0.2583796 ],
       [-0.22761738, -0.13269596, -0.02961969],
       [ 0.17413345, -0.3224947 , -0.02875605]], dtype=float32)

## Cross-correlation

In [5]:
conv_pytorch(a.view(1, 1, 3, 3))

tensor([[[[-1.1027]]]])

In [6]:
correlate2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[-1.1026558]], dtype=float32)

# Real convolution

In [7]:
convolve2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[-0.2611365]], dtype=float32)

In [8]:
a_mod = torch.tensor([[3.3, 3.2, 3.1],
                      [2.3, 2.2, 2.1],
                      [1.3, 1.2, 1.1]])


conv_pytorch(a_mod.view(1, 1, 3, 3))

tensor([[[[-0.2611]]]])